/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yk_cmake_sample_MainActivity */

#ifndef _Included_com_yk_cmake_sample_MainActivity
#define _Included_com_yk_cmake_sample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yk_cmake_sample_MainActivity
 * Method:    getC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yk_cmake_1sample_MainActivity_getC
  (JNIEnv *, jclass);

/*
 * Class:     com_yk_cmake_sample_MainActivity
 * Method:    getCAddAdd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yk_cmake_1sample_MainActivity_getCAddAdd
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
