/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yk_ndk_sample_MainActivity */

#ifndef _Included_com_yk_ndk_sample_MainActivity
#define _Included_com_yk_ndk_sample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yk_ndk_sample_MainActivity
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yk_ndk_1sample_MainActivity_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
